### ISSUE TITLE
Refactoring Compiler to Gradle

### ISSUE THREAD

**Issue by stachu540** [stachu540/HiRezAPI#13]
### To-Do steps refactoring **Gradle** compiler
* [x] Refactoring compiler
* [x] Deprecating Maven Central
* [x] Refactoring package name
* [x] Planning use JCenter for Android's.
* [x] Using `Jitpack.io` - for downloading package
