### ISSUE TITLE
v4 Tracker

### ISSUE THREAD

**Issue by stachu540** [stachu540/HiRezAPI#95]
- [ ] Refactor into Kotlin (1.4)
- [ ] Response result using (one of these):
  - [ ] `kotlinx.coroutines`
  - [ ] Project Reactor
- [ ] Examples - usage
- [ ] Enhance `SessionStorage` to SAM convention
